#!/bin/bash

cd /var/www/decomission/test/

git fetch --all && git checkout composer.lock && git stash && git checkout v8.4.1 && git stash pop

sudo chown -R ubuntu:www-data storage/ bootstrap/ && sudo chmod -R 775 storage/ bootstrap/

